export const identityServiceItems = [
  {
    id: 'identity-01',
    slot: 1,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/01.webp',
    title: 'Corporate Identity',
    gridArea: 'item1',
    imageClassName: 'object-right',
    className: 'bg-maroon',
    desktopGrid: 'col-span-2 row-span-2',
  },
  {
    id: 'identity-02',
    slot: 2,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/02.webp',
    title: 'Brand Design',
    gridArea: 'item2',
    imageClassName: 'object-right',
    className: 'bg-beige',
    desktopGrid: 'col-span-1 row-span-1',
  },
  {
    id: 'identity-03',
    slot: 3,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/03.webp',
    title: 'Premium Packaging',
    gridArea: 'item3',
    imageClassName: 'object-right',
    className: 'bg-main-white',
    desktopGrid: 'col-span-1 row-span-1',
  },
  {
    id: 'identity-04',
    slot: 4,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/04.webp',
    title: 'Custom Solutions',
    gridArea: 'item4',
    imageClassName: 'object-right',
    className: 'bg-main-yellow',
    desktopGrid: 'col-span-1 row-span-1',
  },
  {
    id: 'identity-05',
    slot: 5,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/05.webp',
    title: 'Luxury Experience',
    gridArea: 'item5',
    imageClassName: 'object-right',
    className: 'bg-maroon',
    desktopGrid: 'col-span-1 row-span-1',
  },
  {
    id: 'identity-08',
    slot: 6,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/08.webp',
    title: 'Excellence Standard',
    gridArea: 'item8',
    className: 'bg-main-yellow',
    imageClassName: 'object-right',
    desktopGrid: 'col-span-1 row-span-2',
  },
  {
    id: 'identity-06',
    slot: 7,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/06.webp',
    title: 'Professional Service',
    gridArea: 'item6',
    imageClassName: 'object-right',
    className: 'bg-beige',
    desktopGrid: 'col-span-1 row-span-1',
  },
  {
    id: 'identity-07',
    slot: 8,
    image: 'https://images.giftoryth.com/giftoryth-public/images/IDENTITY_SERVICE/07.webp',
    title: 'Quality Assurance',
    gridArea: 'item7',
    imageClassName: 'object-right',
    className: 'bg-main-white',
    desktopGrid: 'col-span-1 row-span-1',
  },
];
